language: cpp
dist: xenial
compiler: gcc
sudo: true
before_install:
- chmod +x build.sh 

install:
  - sudo apt-get install clang

script: 
  - ./build.sh
  - sonar-scanner -X
  
addons:
   sonarcloud:
   organization: "Azalanel"
   token "0b5cc4b48f6195e3eef1a6c24290800e5af2dd02"
